const items = [
  {
    //warrior gear
    tier: 0,
    class: "Warrior",
    type: "weapon",
    name: "Fists",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Aluminium", 40],
  },
  {
    tier: 0,
    class: "Warrior",
    type: "gloves",
    name: "No Vambraces",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Aluminium", 20],
  },
  {
    tier: 0,
    class: "Warrior",
    type: "helmet",
    name: "No Helm",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Aluminium", 20],
  },
  {
    tier: 0,
    class: "Warrior",
    type: "body",
    name: "No Armour",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Aluminium", 20],
  },
  {
    tier: 0,
    class: "Warrior",
    type: "legs",
    name: "No Legs",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Aluminium", 20],
  },
  {
    tier: 0,
    class: "Warrior",
    type: "boots",
    name: "No Boots",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Aluminium", 20],
  },
  {
    tier: 1,
    class: "Warrior",
    type: "weapon",
    name: "Aluminium Foil",
    atk: 3,
    mhp: 0,
    aspd: 0.9,
    upcost: ["Bronze", 200],
  },
  {
    tier: 1,
    class: "Warrior",
    type: "gloves",
    name: "Aluminium Vambraces",
    atk: 2,
    mhp: 25,
    aspd: 0.95,
    upcost: ["Bronze", 100],
  },
  {
    tier: 1,
    class: "Warrior",
    type: "helmet",
    name: "Aluminium Helm",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Bronze", 100],
  },
  {
    tier: 1,
    class: "Warrior",
    type: "body",
    name: "Aluminium Cuirass",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Bronze", 100],
  },
  {
    tier: 1,
    class: "Warrior",
    type: "legs",
    name: "Aluminium Tasset",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Bronze", 100],
  },
  {
    tier: 1,
    class: "Warrior",
    type: "boots",
    name: "Aluminium Sabatons",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Bronze", 100],
  },
  {
    tier: 2,
    class: "Warrior",
    type: "weapon",
    name: "Bronze Broadsword",
    atk: 10,
    mhp: 25,
    aspd: 0.8,
    upcost: ["Steel", 1000],
  },
  {
    tier: 2,
    class: "Warrior",
    type: "gloves",
    name: "Bronze Vambraces",
    atk: 4,
    mhp: 50,
    aspd: 0.9,
    upcost: ["Steel", 500],
  },
  {
    tier: 2,
    class: "Warrior",
    type: "helmet",
    name: "Bronze Helm",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Steel", 500],
  },
  {
    tier: 2,
    class: "Warrior",
    type: "body",
    name: "Bronze Cuirass",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Steel", 500],
  },
  {
    tier: 2,
    class: "Warrior",
    type: "legs",
    name: "Bronze Tasset",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Steel", 500],
  },
  {
    tier: 2,
    class: "Warrior",
    type: "boots",
    name: "Bronze Sabatons",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Steel", 500],
  },
  {
    tier: 3,
    class: "Warrior",
    type: "weapon",
    name: "Steel Broadsword",
    atk: 30,
    mhp: 100,
    aspd: 0.7,
    upcost: ["Titanium", 5000],
  },
  {
    tier: 3,
    class: "Warrior",
    type: "gloves",
    name: "Steel Vambraces",
    atk: 10,
    mhp: 150,
    aspd: 0.85,
    upcost: ["Titanium", 2000],
  },
  {
    tier: 3,
    class: "Warrior",
    type: "helmet",
    name: "Steel Helm",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Titanium", 2000],
  },
  {
    tier: 3,
    class: "Warrior",
    type: "helmet",
    name: "Steel Helm",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Titanium", 2000],
  },
  {
    tier: 3,
    class: "Warrior",
    type: "body",
    name: "Steel Cuirass",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Titanium", 2000],
  },
  {
    tier: 3,
    class: "Warrior",
    type: "legs",
    name: "Steel Tasset",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Titanium", 2000],
  },
  {
    tier: 3,
    class: "Warrior",
    type: "boots",
    name: "Steel Sabatons",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Titanium", 2000],
  },
  {
    tier: 4,
    class: "Warrior",
    type: "weapon",
    name: "Titanium Broadsword",
    atk: 100,
    mhp: 300,
    aspd: 0.6,
    upcost: ["Tungsten", 20000],
  },
  {
    tier: 4,
    class: "Warrior",
    type: "gloves",
    name: "Titanium Vambraces",
    atk: 50,
    mhp: 450,
    aspd: 0.8,
    upcost: ["Tungsten", 10000],
  },
  {
    tier: 4,
    class: "Warrior",
    type: "helmet",
    name: "Titanium Helm",
    atk: 10,
    mhp: 750,
    aspd: 0.92,
    upcost: ["Tungsten", 10000],
  },
  {
    tier: 4,
    class: "Warrior",
    type: "body",
    name: "Titanium Cuirass",
    atk: 10,
    mhp: 750,
    aspd: 0.92,
    upcost: ["Tungsten", 10000],
  },
  {
    tier: 4,
    class: "Warrior",
    type: "legs",
    name: "Titanium Tasset",
    atk: 10,
    mhp: 750,
    aspd: 0.92,
    upcost: ["Tungsten", 10000],
  },
  {
    tier: 4,
    class: "Warrior",
    type: "boots",
    name: "Titanium Sabatons",
    atk: 10,
    mhp: 750,
    aspd: 0.92,
    upcost: ["Tungsten", 10000],
  },
  {
    tier: 5,
    class: "Warrior",
    type: "weapon",
    name: "Tungsten Broadsword",
    atk: 1000,
    mhp: 3500,
    aspd: 0.5,
    upcost: ["Diamond Weapon", 1],
  },
  {
    tier: 5,
    class: "Warrior",
    type: "gloves",
    atk: 500,
    mhp: 6500,
    aspd: 0.75,
    upcost: ["Diamond Gloves", 1],
  },
  {
    tier: 5,
    class: "Warrior",
    type: "helmet",
    name: "Tungsten Helm",
    atk: 100,
    mhp: 10000,
    aspd: 0.9,
    upcost: ["Diamond Helmet", 1],
  },
  {
    tier: 5,
    class: "Warrior",
    type: "body",
    name: "Tungsten Cuirass",
    atk: 100,
    mhp: 10000,
    aspd: 0.9,
    upcost: ["Diamond Chestpiece", 1],
  },
  {
    tier: 5,
    class: "Warrior",
    type: "legs",
    name: "Tungsten Tasset",
    atk: 100,
    mhp: 10000,
    aspd: 0.9,
    upcost: ["Diamond Legpiece", 1],
  },
  {
    tier: 5,
    class: "Warrior",
    type: "boots",
    name: "Tungsten Sabatons",
    atk: 100,
    mhp: 10000,
    aspd: 0.9,
    upcost: ["Diamond Boots", 1],
  },
  {
    tier: 6,
    class: "Warrior",
    type: "weapon",
    name: "Diamond Sword",
    atk: 10000,
    mhp: 35000,
    aspd: 0.4,
    upcost: ["Prismatic Weapon", 1],
  },
  {
    tier: 6,
    class: "Warrior",
    type: "gloves",
    name: "Diamond Vambraces",
    atk: 5000,
    mhp: 65000,
    aspd: 0.7,
    upcost: ["Prismatic Gloves", 1],
  },
  {
    tier: 6,
    class: "Warrior",
    type: "helmet",
    name: "Diamond Helm",
    atk: 1000,
    mhp: 100000,
    aspd: 0.88,
    upcost: ["Prismatic Helmet", 1],
  },
  {
    tier: 6,
    class: "Warrior",
    type: "body",
    name: "Diamond Cuirass",
    atk: 1000,
    mhp: 100000,
    aspd: 0.88,
    upcost: ["Prismatic Chestpiece", 1],
  },
  {
    tier: 6,
    class: "Warrior",
    type: "legs",
    name: "Diamond Tasset",
    atk: 1000,
    mhp: 100000,
    aspd: 0.88,
    upcost: ["Prismatic Legpiece", 1],
  },
  {
    tier: 6,
    class: "Warrior",
    type: "boots",
    name: "Diamond Sabatons",
    atk: 1000,
    mhp: 100000,
    aspd: 0.88,
    upcost: ["Prismatic Boots", 1],
  },
  {
    tier: 7,
    class: "Warrior",
    type: "weapon",
    name: "Prismatic Sword",
    atk: 100000,
    mhp: 350000,
    aspd: 0.3,
    upcost: ["Olympian Weapon", 1],
  },
  {
    tier: 7,
    class: "Warrior",
    type: "gloves",
    name: "Prismatic Vambraces",
    atk: 50000,
    mhp: 650000,
    aspd: 0.65,
    upcost: ["Olympian Gloves", 1],
  },
  {
    tier: 7,
    class: "Warrior",
    type: "helmet",
    name: "Prismatic Helm",
    atk: 10000,
    mhp: 1000000,
    aspd: 0.86,
    upcost: ["Olympian Helmet", 1],
  },
  {
    tier: 7,
    class: "Warrior",
    type: "body",
    name: "Prismatic Cuirass",
    atk: 10000,
    mhp: 1000000,
    aspd: 0.86,
    upcost: ["Olympian Chestpiece", 1],
  },
  {
    tier: 7,
    class: "Warrior",
    type: "legs",
    name: "Prismatic Tasset",
    atk: 10000,
    mhp: 1000000,
    aspd: 0.86,
    upcost: ["Olympian Legpiece", 1],
  },
  {
    tier: 7,
    class: "Warrior",
    type: "boots",
    name: "Prismatic Sabatons",
    atk: 10000,
    mhp: 1000000,
    aspd: 0.86,
    upcost: ["Olympian Boots", 1],
  },
  {
    tier: 8,
    class: "Warrior",
    type: "weapon",
    name: "Olympian Sword",
    atk: 1000000,
    mhp: 3500000,
    aspd: 0.2,
    upcost: ["Starforged Weapon", 1],
  },
  {
    tier: 8,
    class: "Warrior",
    type: "gloves",
    name: "Olympian Vambraces",
    atk: 500000,
    mhp: 6500000,
    aspd: 0.6,
    upcost: ["Starforged Gloves", 1],
  },
  {
    tier: 8,
    class: "Warrior",
    type: "helmet",
    name: "Olympian Helm",
    atk: 100000,
    mhp: 10000000,
    aspd: 0.84,
    upcost: ["Starforged Helmet", 1],
  },
  {
    tier: 8,
    class: "Warrior",
    type: "body",
    name: "Olympian Cuirass",
    atk: 100000,
    mhp: 10000000,
    aspd: 0.84,
    upcost: ["Starforged Chestpiece", 1],
  },
  {
    tier: 8,
    class: "Warrior",
    type: "legs",
    name: "Olympian Tasset",
    atk: 100000,
    mhp: 10000000,
    aspd: 0.84,
    upcost: ["Starforged Legpiece", 1],
  },
  {
    tier: 8,
    class: "Warrior",
    type: "boots",
    name: "Olympian Sabatons",
    atk: 100000,
    mhp: 10000000,
    aspd: 0.84,
    upcost: ["Starforged Boots", 1],
  },
  {
    tier: 9,
    class: "Warrior",
    type: "weapon",
    name: "Starforged Sword",
    atk: 10000000,
    mhp: 35000000,
    aspd: 0.1,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Warrior",
    type: "gloves",
    name: "Starforged Vambraces",
    atk: 5000000,
    mhp: 65000000,
    aspd: 0.5,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Warrior",
    type: "helmet",
    name: "Starforged Helm",
    atk: 1000000,
    mhp: 100000000,
    aspd: 0.8,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Warrior",
    type: "body",
    name: "Starforged Cuirass",
    atk: 1000000,
    mhp: 100000000,
    aspd: 0.8,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Warrior",
    type: "legs",
    name: "Starforged Tasset",
    atk: 1000000,
    mhp: 100000000,
    aspd: 0.8,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Warrior",
    type: "boots",
    name: "Starforged Sabatons",
    atk: 1000000,
    mhp: 100000000,
    aspd: 0.8,
    upcost: ["Max Tier!", 1],
  },

  //hunter gear
  {
    tier: 0,
    class: "Hunter",
    type: "weapon",
    name: "Slingshot",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Balsa", 40],
  },
  {
    tier: 0,
    class: "Hunter",
    type: "gloves",
    name: "No Vambraces",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Leather", 20],
  },
  {
    tier: 0,
    class: "Hunter",
    type: "helmet",
    name: "No Coif",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Leather", 20],
  },
  {
    tier: 0,
    class: "Hunter",
    type: "body",
    name: "No Armour",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Leather", 20],
  },
  {
    tier: 0,
    class: "Hunter",
    type: "legs",
    name: "No Greaves",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Leather", 20],
  },
  {
    tier: 0,
    class: "Hunter",
    type: "boots",
    name: "No Shoes",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Leather", 20],
  },
  {
    tier: 1,
    class: "Hunter",
    type: "weapon",
    name: "Balsa Longbow",
    atk: 3,
    mhp: 0,
    aspd: 0.9,
    upcost: ["Redwood", 200],
  },
  {
    tier: 1,
    class: "Hunter",
    type: "gloves",
    name: "Leather Bracers",
    atk: 2,
    mhp: 25,
    aspd: 0.95,
    upcost: ["Snakehide", 100],
  },
  {
    tier: 1,
    class: "Hunter",
    type: "helmet",
    name: "Leather Coif",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Snakehide", 100],
  },
  {
    tier: 1,
    class: "Hunter",
    type: "body",
    name: "Leather Armour",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Snakehide", 100],
  },
  {
    tier: 1,
    class: "Hunter",
    type: "legs",
    name: "Leather Greaves",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Snakehide", 100],
  },
  {
    tier: 1,
    class: "Hunter",
    type: "boots",
    name: "Leather Sandals",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Snakehide", 100],
  },
  {
    tier: 2,
    class: "Hunter",
    type: "weapon",
    name: "Redwood Longbow",
    atk: 10,
    mhp: 25,
    aspd: 0.8,
    upcost: ["Maple", 1000],
  },
  {
    tier: 2,
    class: "Hunter",
    type: "gloves",
    name: "Snakehide Bracers",
    atk: 4,
    mhp: 50,
    aspd: 0.9,
    upcost: ["Croc Skin", 500],
  },
  {
    tier: 2,
    class: "Hunter",
    type: "helmet",
    name: "Snakehide Coif",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Croc Skin", 500],
  },
  {
    tier: 2,
    class: "Hunter",
    type: "body",
    name: "Snakehide Armour",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Croc Skin", 500],
  },
  {
    tier: 2,
    class: "Hunter",
    type: "legs",
    name: "Snakehide Greaves",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Croc Skin", 500],
  },
  {
    tier: 2,
    class: "Hunter",
    type: "boots",
    name: "Snakehide Boots",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Croc Skin", 500],
  },
  {
    tier: 3,
    class: "Hunter",
    type: "weapon",
    name: "Maple Longbow",
    atk: 30,
    mhp: 100,
    aspd: 0.7,
    upcost: ["Purpleheart", 5000],
  },
  {
    tier: 3,
    class: "Hunter",
    type: "gloves",
    name: "Crocodile Bracers",
    atk: 10,
    mhp: 150,
    aspd: 0.85,
    upcost: ["Drakeskin", 2000],
  },
  {
    tier: 3,
    class: "Hunter",
    type: "helmet",
    name: "Crocodile Coif",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Drakeskin", 2000],
  },
  {
    tier: 3,
    class: "Hunter",
    type: "body",
    name: "Crocodile Armour",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Drakeskin", 2000],
  },
  {
    tier: 3,
    class: "Hunter",
    type: "legs",
    name: "Crocodile Greaves",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Drakeskin", 2000],
  },
  {
    tier: 3,
    class: "Hunter",
    type: "boots",
    name: "Crocodile Boots",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Drakeskin", 2000],
  },
  {
    tier: 4,
    class: "Hunter",
    type: "weapon",
    name: "Purpleheart Longbow",
    atk: 100,
    mhp: 300,
    aspd: 0.6,
    upcost: ["Snakewood", 20000],
  },
  {
    tier: 4,
    class: "Hunter",
    type: "gloves",
    name: "Drakeskin Bracers",
    atk: 50,
    mhp: 450,
    aspd: 0.8,
    upcost: ["Dragonhide", 10000],
  },
  {
    tier: 4,
    class: "Hunter",
    type: "helmet",
    name: "Drakeskin Coif",
    atk: 10,
    mhp: 750,
    aspd: 0.92,
    upcost: ["Dragonhide", 10000],
  },
  {
    tier: 4,
    class: "Hunter",
    type: "body",
    name: "Drakeskin Armour",
    atk: 10,
    mhp: 750,
    aspd: 0.92,
    upcost: ["Dragonhide", 10000],
  },
  {
    tier: 4,
    class: "Hunter",
    type: "legs",
    name: "Drakeskin Greaves",
    atk: 10,
    mhp: 750,
    aspd: 0.92,
    upcost: ["Dragonhide", 10000],
  },
 
   {
    tier: 4,
    class: "Hunter",
    type: "boots",
    name: "Drakeskin Boots",
    atk: 10,
    mhp: 750,
    aspd: 0.92,
    upcost: ["Dragonhide", 10000],
  },
  {
    tier: 5,
    class: "Hunter",
    type: "weapon",
    name: "Snakewood Longbow",
    atk: 1000,
    mhp: 3500,
    aspd: 0.5,
    upcost: ["Diamond Weapon", 1],
  },
  {
    tier: 5,
    class: "Hunter",
    type: "gloves",
    name: "Dragonhide Bracers",
    atk: 500,
    mhp: 6500,
    aspd: 0.75,
    upcost: ["Diamond Gloves", 1],
  },
  {
  tier: 5,
  class: "Hunter",
  type: "helmet",
  name: "Dragonhide Coif",
  atk: 100,
  mhp: 10000,
  aspd: 0.9,
  upcost: ["Diamond Helmet", 1],
},
{
  tier: 5,
  class: "Hunter",
  type: "body",
  name: "Dragonhide Armour",
  atk: 100,
  mhp: 10000,
  aspd: 0.9,
  upcost: ["Diamond Chestpiece", 1],
},
{
  tier: 5,
  class: "Hunter",
  type: "legs",
  name: "Dragonhide Greaves",
  atk: 100,
  mhp: 10000,
  aspd: 0.9,
  upcost: ["Diamond Legpiece", 1],
},
{
  tier: 5,
  class: "Hunter",
  type: "boots",
  name: "Dragonhide Boots",
  atk: 100,
  mhp: 10000,
  aspd: 0.9,
  upcost: ["Diamond Boots", 1],
},
{
  tier: 6,
  class: "Hunter",
  type: "weapon",
  name: "Diamond Longbow",
  atk: 10000,
  mhp: 35000,
  aspd: 0.4,
  upcost: ["Prismatic Weapon", 1],
},
{
  tier: 6,
  class: "Hunter",
  type: "gloves",
  name: "Diamond Bracers",
  atk: 5000,
  mhp: 65000,
  aspd: 0.7,
  upcost: ["Prismatic Gloves", 1],
},
{
  tier: 6,
  class: "Hunter",
  type: "helmet",
  name: "Diamond Coif",
  atk: 1000,
  mhp: 100000,
  aspd: 0.88,
  upcost: ["Prismatic Helmet", 1],
},
{
  tier: 6,
  class: "Hunter",
  type: "body",
  name: "Diamond Armour",
  atk: 1000,
  mhp: 100000,
  aspd: 0.88,
  upcost: ["Prismatic Chestpiece", 1],
},
{
  tier: 6,
  class: "Hunter",
  type: "legs",
  name: "Diamond Greaves",
  atk: 1000,
  mhp: 100000,
  aspd: 0.88,
  upcost: ["Prismatic Legpiece", 1],
},
{
  tier: 6,
  class: "Hunter",
  type: "boots",
  name: "Diamond Boots",
  atk: 1000,
  mhp: 100000,
  aspd: 0.88,
  upcost: ["Prismatic Boots", 1],
},
{
  tier: 7,
  class: "Hunter",
  type: "weapon",
  name: "Prismatic Longbow",
  atk: 100000,
  mhp: 350000,
  aspd: 0.3,
  upcost: ["Olympian Weapon", 1],
},
{
  tier: 7,
  class: "Hunter",
  type: "gloves",
  name: "Prismatic Bracers",
  atk: 50000,
  mhp: 650000,
  aspd: 0.65,
  upcost: ["Olympian Gloves", 1],
},
{
  tier: 7,
  class: "Hunter",
  type: "helmet",
  name: "Prismatic Coif",
  atk: 10000,
  mhp: 1000000,
  aspd: 0.86,
  upcost: ["Olympian Helmet", 1],
},
{
  tier: 7,
  class: "Hunter",
  type: "body",
  name: "Prismatic Armour",
  atk: 10000,
  mhp: 1000000,
  aspd: 0.86,
  upcost: ["Olympian Chestpiece", 1],
},
{
  tier: 7,
  class: "Hunter",
  type: "legs",
  name: "Prismatic Greaves",
  atk: 10000,
  mhp: 1000000,
  aspd: 0.86,
  upcost: ["Olympian Legpiece", 1],
},
{
  tier: 7,
  class: "Hunter",
  type: "boots",
  name: "Prismatic Boots",
  atk: 10000,
  mhp: 1000000,
  aspd: 0.86,
  upcost: ["Olympian Boots", 1],
},
{
  tier: 8,
  class: "Hunter",
  type: "weapon",
  name: "Olympian Longbow",
  atk: 1000000,
  mhp: 3500000,
  aspd: 0.2,
  upcost: ["Starforged Weapon", 1],
},
{
  tier: 8,
  class: "Hunter",
  type: "gloves",
  name: "Olympian Bracers",
  atk: 500000,
  mhp: 6500000,
  aspd: 0.6,
  upcost: ["Starforged Gloves", 1],
},
{
  tier: 8,
  class: "Hunter",
  type: "helmet",
  name: "Olympian Coif",
  atk: 100000,
  mhp: 10000000,
  aspd: 0.84,
  upcost: ["Starforged Helmet", 1],
},
{
  tier: 8,
  class: "Hunter",
  type: "body",
  name: "Olympian Armour",
  atk: 100000,
  mhp: 10000000,
  aspd: 0.84,
  upcost: ["Starforged Chestpiece", 1],
},
{
  tier: 8,
  class: "Hunter",
  type: "legs",
  name: "Olympian Greaves",
  atk: 100000,
  mhp: 10000000,
  aspd: 0.84,
  upcost: ["Starforged Legpiece", 1],
},
{
  tier: 8,
  class: "Hunter",
  type: "boots",
  name: "Olympian Boots",
  atk: 100000,
  mhp: 10000000,
  aspd: 0.84,
  upcost: ["Starforged Boots", 1],
},
{
  tier: 9,
  class: "Hunter",
  type: "weapon",
  name: "Starforged Longbow",
  atk: 10000000,
  mhp: 35000000,
  aspd: 0.1,
  upcost: ["Max Tier!", 1],
},
{
  tier: 9,
  class: "Hunter",
  type: "gloves",
  name: "Starforged Bracers",
  atk: 5000000,
  mhp: 65000000,
  aspd: 0.5,
  upcost: ["Max Tier!", 1],
},
{
  tier: 9,
  class: "Hunter",
  type: "helmet",
  name: "Starforged Coif",
  atk: 1000000,
  mhp: 100000000,
  aspd: 0.8,
  upcost: ["Max Tier!", 1],
},
{
  tier: 9,
  class: "Hunter",
  type: "body",
  name: "Starforged Armour",
  atk: 1000000,
  mhp: 100000000,
  aspd: 0.8,
  upcost: ["Max Tier!", 1],
},
{
  tier: 9,
  class: "Hunter",
  type: "legs",
  name: "Starforged Greaves",
  atk: 1000000,
  mhp: 100000000,
  aspd: 0.8,
  upcost: ["Max Tier!", 1],
},
{
  tier: 9,
  class: "Hunter",
  type: "boots",
  name: "Starforged Boots",
  atk: 1000000,
  mhp: 100000000,
  aspd: 0.8,
  upcost: ["Max Tier!", 1],
},
  
  // wizard gear
  {
    tier: 0,
    class: "Wizard",
    type: "weapon",
    name: "A Stick",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Balsa", 40],
  },
  {
    tier: 0,
    class: "Wizard",
    type: "gloves",
    name: "No Gloves",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Jute", 20],
  },
  {
    tier: 0,
    class: "Wizard",
    type: "helmet",
    name: "No Hat",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Jute", 20],
  },
  {
    tier: 0,
    class: "Wizard",
    type: "body",
    name: "No Robes",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Jute", 20],
  },
  {
    tier: 0,
    class: "Wizard",
    type: "legs",
    name: "No Skirt",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Jute", 20],
  },
  {
    tier: 0,
    class: "Wizard",
    type: "boots",
    name: "No Shoes",
    atk: 0,
    mhp: 0,
    aspd: 1,
    upcost: ["Leather", 20],
  },
  {
    tier: 1,
    class: "Wizard",
    type: "weapon",
    name: "Balsa Staff",
    atk: 3,
    mhp: 0,
    aspd: 0.9,
    upcost: ["Redwood", 200],
  },
  {
    tier: 1,
    class: "Wizard",
    type: "gloves",
    name: "Jute Gloves",
    atk: 2,
    mhp: 25,
    aspd: 0.95,
    upcost: ["Cotton", 100],
  },
  {
    tier: 1,
    class: "Wizard",
    type: "helmet",
    name: "Jute Hat",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Cotton", 100],
  },
  {
    tier: 1,
    class: "Wizard",
    type: "body",
    name: "Jute Robes",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Cotton", 100],
  },
  {
    tier: 1,
    class: "Wizard",
    type: "legs",
    name: "Jute Robeskirt",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Cotton", 100],
  },
  {
    tier: 1,
    class: "Wizard",
    type: "boots",
    name: "Leather Shoes",
    atk: 1,
    mhp: 25,
    aspd: 0.98,
    upcost: ["Snakehide", 100],
  },
  {
    tier: 2,
    class: "Wizard",
    type: "weapon",
    name: "Redwood Staff",
    atk: 10,
    mhp: 25,
    aspd: 0.8,
    upcost: ["Maple", 1000],
  },
  {
    tier: 2,
    class: "Wizard",
    type: "gloves",
    name: "Cotton Gloves",
    atk: 4,
    mhp: 50,
    aspd: 0.9,
    upcost: ["Cashmere", 500],
  },
  {
    tier: 2,
    class: "Wizard",
    type: "helmet",
    name: "Cotton Hat",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Cashmere", 500],
  },
  {
    tier: 2,
    class: "Wizard",
    type: "body",
    name: "Cotton Robes",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Cashmere", 500],
  },
  {
    tier: 2,
    class: "Wizard",
    type: "legs",
    name: "Cotton Robeskirt",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Cashmere", 500],
  },
  {
    tier: 2,
    class: "Wizard",
    type: "boots",
    name: "Snakehide Shoes",
    atk: 2,
    mhp: 75,
    aspd: 0.96,
    upcost: ["Croc Skin", 500],
  },
  {
    tier: 3,
    class: "Wizard",
    type: "weapon",
    name: "Maple Staff",
    atk: 30,
    mhp: 100,
    aspd: 0.7,
    upcost: ["Purpleheart", 5000],
  },
  {
    tier: 3,
    class: "Wizard",
    type: "gloves",
    name: "Cashmere Gloves",
    atk: 10,
    mhp: 150,
    aspd: 0.85,
    upcost: ["Silk", 2000],
  },
  {
    tier: 3,
    class: "Wizard",
    type: "helmet",
    name: "Cashmere Hat",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Silk", 2000],
  },
  {
    tier: 3,
    class: "Wizard",
    type: "body",
    name: "Cashmere Outside",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Silk", 2000],
  },
  {
    tier: 3,
    class: "Wizard",
    type: "legs",
    name: "Cashmere Robeskirt",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Silk", 2000],
  },
  {
    tier: 3,
    class: "Wizard",
    type: "boots",
    name: "Designer Crocs",
    atk: 5,
    mhp: 300,
    aspd: 0.94,
    upcost: ["Drakeskin", 2000],
  },
  {
    tier: 4,
    class: "Wizard",
    type: "weapon",
    name: "Purpleheart Staff",
    atk: 200,
    mhp: 350,
    aspd: 0.6,
    upcost: ["Snakewood", 20000],
  },
  {
    tier: 4,
    class: "Wizard",
    type: "gloves",
    name: "Silk Gloves",
    atk: 100,
    mhp: 650,
    aspd: 0.8,
    upcost: ["Vicu\xF1a", 10000],
  },
  {
    tier: 4,
    class: "Wizard",
    type: "helmet",
    name: "Silk Hat",
    atk: 20,
    mhp: 1000,
    aspd: 0.92,
    upcost: ["Vicu\xF1a", 10000],
  },
  {
    tier: 4,
    class: "Wizard",
    type: "body",
    name: "Silk Robe",
    atk: 20,
    mhp: 1000,
    aspd: 0.92,
    upcost: ["Vicu\xF1a", 10000],
  },
  {
    tier: 4,
    class: "Wizard",
    type: "legs",
    name: "Silk Robeskirt",
    atk: 20,
    mhp: 1000,
    aspd: 0.92,
    upcost: ["Vicu\xF1a", 10000],
  },
  {
    tier: 4,
    class: "Wizard",
    type: "boots",
    name: "Drakeskin Shoes",
    atk: 20,
    mhp: 1000,
    aspd: 0.92,
    upcost: ["Dragonhide", 10000],
  },
  {
    tier: 5,
    class: "Wizard",
    type: "weapon",
    name: "Snakewood Staff",
    atk: 1000,
    mhp: 3500,
    aspd: 0.5,
    upcost: ["Diamond Weapon", 1],
  },
  {
    tier: 5,
    class: "Wizard",
    type: "gloves",
    name: "Vicu\xF1a Gloves",
    atk: 500,
    mhp: 6500,
    aspd: 0.75,
    upcost: ["Diamond Gloves", 1],
  },
  {
    tier: 5,
    class: "Wizard",
    type: "helmet",
    name: "Vicu\xF1a Hat",
    atk: 100,
    mhp: 10000,
    aspd: 0.9,
    upcost: ["Diamond Helmet", 1],
  },
  {
    tier: 5,
    class: "Wizard",
    type: "body",
    name: "Vicu\xF1a Robes",
    atk: 100,
    mhp: 10000,
    aspd: 0.9,
    upcost: ["Diamond Chestpiece", 1],
  },
  {
    tier: 5,
    class: "Wizard",
    type: "legs",
    name: "Vicu\xF1a Robeskirt",
    atk: 100,
    mhp: 10000,
    aspd: 0.9,
    upcost: ["Diamond Legpiece", 1],
  },
  {
    tier: 5,
    class: "Wizard",
    type: "boots",
    name: "Dragonhide Shoes",
    atk: 100,
    mhp: 10000,
    aspd: 0.9,
    upcost: ["Diamond Boots", 1],
  },
  {
    tier: 6,
    class: "Wizard",
    type: "weapon",
    name: "Diamond Staff",
    atk: 10000,
    mhp: 35000,
    aspd: 0.4,
    upcost: ["Prismatic Weapon", 1],
  },
  {
    tier: 6,
    class: "Wizard",
    type: "gloves",
    name: "Diamond Gloves",
    atk: 5000,
    mhp: 65000,
    aspd: 0.7,
    upcost: ["Prismatic Gloves", 1],
  },
  {
    tier: 6,
    class: "Wizard",
    type: "helmet",
    name: "Diamond Hat",
    atk: 1000,
    mhp: 100000,
    aspd: 0.88,
    upcost: ["Prismatic Helmet", 1],
  },
  {
    tier: 6,
    class: "Wizard",
    type: "body",
    name: "Diamond Robes",
    atk: 1000,
    mhp: 100000,
    aspd: 0.88,
    upcost: ["Prismatic Chestpiece", 1],
  },
  {
    tier: 6,
    class: "Wizard",
    type: "legs",
    name: "Diamond Robeskirt",
    atk: 1000,
    mhp: 100000,
    aspd: 0.88,
    upcost: ["Prismatic Legpiece", 1],
  },
  {
    tier: 6,
    class: "Wizard",
    type: "boots",
    name: "Diamond Shoes",
    atk: 1000,
    mhp: 100000,
    aspd: 0.88,
    upcost: ["Prismatic Boots", 1],
  },
  {
    tier: 7,
    class: "Wizard",
    type: "weapon",
    name: "Prismatic Staff",
    atk: 100000,
    mhp: 350000,
    aspd: 0.3,
    upcost: ["Olympian Weapon", 1],
  },
  {
    tier: 7,
    class: "Wizard",
    type: "gloves",
    name: "Prismatic Gloves",
    atk: 50000,
    mhp: 650000,
    aspd: 0.65,
    upcost: ["Olympian Gloves", 1],
  },
  {
    tier: 7,
    class: "Wizard",
    type: "helmet",
    name: "Prismatic Hat",
    atk: 10000,
    mhp: 1000000,
    aspd: 0.86,
    upcost: ["Olympian Helmet", 1],
  },
  {
    tier: 7,
    class: "Wizard",
    type: "body",
    name: "Prismatic Robes",
    atk: 10000,
    mhp: 1000000,
    aspd: 0.86,
    upcost: ["Olympian Chestpiece", 1],
  },
  {
    tier: 7,
    class: "Wizard",
    type: "legs",
    name: "Prismatic Robeskirt",
    atk: 10000,
    mhp: 1000000,
    aspd: 0.86,
    upcost: ["Olympian Legpiece", 1],
  },
  {
    tier: 7,
    class: "Wizard",
    type: "boots",
    name: "Prismatic Shoes",
    atk: 10000,
    mhp: 1000000,
    aspd: 0.86,
    upcost: ["Olympian Boots", 1],
  },
  {
    tier: 8,
    class: "Wizard",
    type: "weapon",
    name: "Olympian Staff",
    atk: 1000000,
    mhp: 3500000,
    aspd: 0.2,
    upcost: ["Starforged Weapon", 1],
  },
  {
    tier: 8,
    class: "Wizard",
    type: "gloves",
    name: "Olympian Gloves",
    atk: 500000,
    mhp: 6500000,
    aspd: 0.6,
    upcost: ["Starforged Gloves", 1],
  },
  {
    tier: 8,
    class: "Wizard",
    type: "helmet",
    name: "Olympian Hat",
    atk: 100000,
    mhp: 10000000,
    aspd: 0.84,
    upcost: ["Starforged Helmet", 1],
  },
  {
    tier: 8,
    class: "Wizard",
    type: "body",
    name: "Olympian Robe",
    atk: 100000,
    mhp: 10000000,
    aspd: 0.84,
    upcost: ["Starforged Chestpiece", 1],
  },
  {
    tier: 8,
    class: "Wizard",
    type: "legs",
    name: "Olympian Robeskirt",
    atk: 100000,
    mhp: 10000000,
    aspd: 0.84,
    upcost: ["Starforged Legpiece", 1],
  },
  {
    tier: 8,
    class: "Wizard",
    type: "boots",
    name: "Olympian Shoes",
    atk: 100000,
    mhp: 10000000,
    aspd: 0.84,
    upcost: ["Starforged Boots", 1],
  },
  {
    tier: 9,
    class: "Wizard",
    type: "weapon",
    name: "Starforged Staff",
    atk: 10000000,
    mhp: 35000000,
    aspd: 0.1,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Wizard",
    type: "gloves",
    name: "Starforged Gloves",
    atk: 5000000,
    mhp: 65000000,
    aspd: 0.5,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Wizard",
    type: "helmet",
    name: "Starforged Hat",
    atk: 1000000,
    mhp: 100000000,
    aspd: 0.8,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Wizard",
    type: "body",
    name: "Starforged Robe",
    atk: 1000000,
    mhp: 100000000,
    aspd: 0.8,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Wizard",
    type: "legs",
    name: "Starforged Robeskirt",
    atk: 1000000,
    mhp: 100000000,
    aspd: 0.8,
    upcost: ["Max Tier!", 1],
  },
  {
    tier: 9,
    class: "Wizard",
    type: "boots",
    name: "Starforged Shoes",
    atk: 1000000,
    mhp: 100000000,
    aspd: 0.8,
    upcost: ["Max Tier!", 1],
  },
];

export default items;
